/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CampaignsCampaignIdSessionsSessionIdRouteImport } from './routes/campaigns/$campaignId/sessions/$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdSessionsSessionIdRoute =
  CampaignsCampaignIdSessionsSessionIdRouteImport.update({
    id: '/campaigns/$campaignId/sessions/$sessionId',
    path: '/campaigns/$campaignId/sessions/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/campaigns/$campaignId/sessions/$sessionId': typeof CampaignsCampaignIdSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/campaigns/$campaignId/sessions/$sessionId': typeof CampaignsCampaignIdSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/campaigns/$campaignId/sessions/$sessionId': typeof CampaignsCampaignIdSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/campaigns/$campaignId/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/campaigns/$campaignId/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/campaigns/$campaignId/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  CampaignsCampaignIdSessionsSessionIdRoute: typeof CampaignsCampaignIdSessionsSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$campaignId/sessions/$sessionId': {
      id: '/campaigns/$campaignId/sessions/$sessionId'
      path: '/campaigns/$campaignId/sessions/$sessionId'
      fullPath: '/campaigns/$campaignId/sessions/$sessionId'
      preLoaderRoute: typeof CampaignsCampaignIdSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  CampaignsCampaignIdSessionsSessionIdRoute:
    CampaignsCampaignIdSessionsSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
